const Cardsdata = [
    {
        id: 1,
        dish: "Black Forest Cake",
        imgdata:"./img/1.jpg",
        address: "Cake",
        includes: "1 piece cake(50g)",
        category: "Dessert/Cake",
        desc:"The Black Forest Cake, also known as Schwarzwalder Kirschtorte, is a decadent dessert that originated in Germany's Black Forest region. It's renowned for its rich layers of chocolate cake, whipped cream, cherries, and a hint of Kirsch (cherry brandy).",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: " 1175 + order placed from here recently",
        price: 50,
        rating: "4.2",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
        qnty:0
    },
    {
        id: 2,
        dish: " Pani Puri",
        imgdata: "./img/2.jpg",
        address: "Street Food",
        includes: "5 pieces puri and pani",
        category: "Snack/Street Food",
        desc:"Pani Puri is celebrated for its explosion of flavors and textures in every bite. The combination of the crunchy puri, spicy and tangy pani (water), sweet tamarind chutney, and savory filling creates a delightful and addictive taste experience.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: " 2525 + order placed from here recently",
        price: 40,
        rating: "3.9",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 3,
        dish: "French Fries",
        imgdata: "./img/3.jpg",
        address: "Pizza, Fast Food, Pasta",
        includes: "100g of French fries with sauce",
        category: "Snack/Fast Food",
        desc:"French Fries are crispy, golden sticks of fried potatoes, loved for their crunchy exterior and fluffy interior. Perfectly seasoned with salt, they are a versatile snack enjoyed with a variety of dips and condiments.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: " 650 + order placed from here recently",
        price: 70,
        rating: "4.2",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 4,
        dish: "Watermelon Juice",
        imgdata: "./img/4.jpg",
        address: "Momos",
        includes: "1 glass of juice(200ml)",
        category: "Beverage/Juice",
        desc:"Watermelon Juice is a refreshing and hydrating beverage made from the sweet and juicy flesh of watermelons. It's perfect for hot summer days, offering a natural source of vitamins and antioxidants.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: " 300 + order placed from here recently",
        price: 40,
        rating: "3.8",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 5,
        dish: "Prawn Curry",
        imgdata: "./img/5.jpg",
        address: "North Indian",
        includes: "One plate(serves 1)",
        category: "Main Course/Seafood",
        desc:" Prawn Curry is a delicious and aromatic dish featuring succulent prawns cooked in a rich, spiced curry sauce. Often made with coconut milk, tomatoes, and a blend of traditional Indian spices, it’s a flavorful and satisfying meal.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: "1050 + order placed from here recently",
        price: 200,
        rating: "4.0",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 6,
        dish: "Fish Fry",
        imgdata: "./img/6.jpg",
        address: "Wraps FastFood, Chines",
        includes: "2 pieces",
        category: "Appetizer/Seafood",
        desc:"Fish Fry is a popular dish featuring fish fillets or whole fish marinated with spices and herbs, then deep-fried until golden and crispy. It's known for its crunchy exterior and tender, flavorful meat inside.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: " 1100 + order placed from here recently",
        price: 200,
        rating: "3.8",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 7,
        dish: "Spicy Pasta",
        imgdata: "./img/7.jpg",
        address: "North Indian, Fast Food",
        includes: "1 plate(serves 1)",
        category: "Main Course/Pasta",
        desc:"Spicy Pasta is a fiery and flavorful dish featuring pasta cooked with a spicy sauce made from tomatoes, garlic, chili flakes, and a variety of herbs and spices. It’s a delightful fusion of Italian pasta with a spicy kick.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: "500 + order placed from here recently",
        price: 100,
        rating: "3.8",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 8,
        dish: "Veg Noodles",
        imgdata: "./img/8.jpg",
        address: "Tea, Coffee, Shake, Beverages",
        includes: "1 plate (serves 1)",
        category: "Main Course/Noodles",
        desc:"Veg Noodles are a popular dish made by stir-frying noodles with a medley of fresh vegetables and flavorful sauces. It's a versatile and quick-to-prepare meal enjoyed for its vibrant taste and texture.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: "500 + order placed from here recently",
        price: 80,
        rating: "3.2",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 9,
        dish: "Boiled Eggs",
        imgdata: "./img/9.jpg",
        address: "Burger, Sandwich, Fast Food",
        includes: "1 egg",
        category: "Snack/Breakfast",
        desc:"Boiled Eggs are a simple and nutritious dish where eggs are cooked in their shells in boiling water until they reach the desired level of doneness. They can be enjoyed on their own or used in various recipes.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: "2525 + order placed from here recently",
        price: 20,
        rating: "3.8",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 10,
        dish: "Samosa",
        imgdata: "./img/10.jpg",
        address: "Burger, Sandwich, Fast Food",
        includes: "1 piece with sauce",
        category: "Snack/Appetizer",
        desc:"Samosa is a popular Indian snack consisting of a crisp, golden pastry filled with a savory mixture of spiced potatoes, peas, and sometimes meat. It's deep-fried to perfection, resulting in a delightful combination of crunchy exterior and flavorful filling.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: "2525 + order placed from here recently",
        price: 20,
        rating: "3.8",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 11,
        dish: "Chicken Wings",
        imgdata: "./img/11.jpg",
        address: "Burger, Sandwich, Fast Food",
        includes: "2 pieces",
        category: "Appetizer/Snack",
        desc:"Chicken Wings are a popular and flavorful dish featuring sections of chicken wings that are typically deep-fried or baked and then coated in a variety of sauces. They are known for their crispy skin and tender meat.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: "2525 + order placed from here recently",
        price: 150,
        rating: "3.8",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 12,
        dish: "Naan",
        imgdata: "./img/12.jpg",
        address: "Burger, Sandwich, Fast Food",
        includes: "1 piece",
        category: "Bread",
        desc:"Naan is a soft and fluffy Indian bread, typically leavened with yeast and baked in a tandoor (clay oven). It's characterized by its slightly chewy texture and distinct charred spots, making it a perfect accompaniment to various Indian dishes.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: "2525 + order placed from here recently",
        price: 20,
        rating: "3.8",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 13,
        dish: "KFC Chicken",
        imgdata: "./img/13.jpg",
        address: "Burger, Sandwich, Fast Food",
        includes: "6 pieces",
        category: "Fast Food/Restaurant",
        desc:"KFC, short for Kentucky Fried Chicken, is a globally renowned fast-food chain famous for its crispy, seasoned fried chicken. With a secret blend of herbs and spices, KFC offers a variety of chicken options, including wings, drumsticks, and sandwiches, served with sides like coleslaw, mashed potatoes, and biscuits.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: "2525 + order placed from here recently",
        price: 210,
        rating: "3.8",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 14,
        dish: "Chicken Kebab",
        imgdata: "./img/14.jpg",
        address: "Burger, Sandwich, Fast Food",
        includes: "2 pieces",
        category: "Appetizer/Entree",
        desc:"Chicken Kebab is a popular dish made by marinating chicken pieces in a flavorful blend of spices, yogurt, and herbs, skewering them, and grilling or baking until tender and juicy. It's known for its succulent texture and aromatic spices.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: "2525 + order placed from here recently",
        price: 150,
        rating: "3.8",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 15,
        dish: "Roast Dosa",
        imgdata: "./img/15.jpg",
        address: "Burger, Sandwich, Fast Food",
        includes: "1 roast",
        category: "Breakfast/Snack",
        desc:"Roast Dosa, also known as Paper Dosa, is a thin and crispy South Indian crepe made from a fermented batter of rice and lentils. It's cooked on a hot griddle until golden brown and served with chutneys and sambar, offering a delightful blend of textures and flavors.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: "2525 + order placed from here recently",
        price: 50,
        rating: "3.8",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 16,
        dish: "Idli with Vada",
        imgdata: "./img/16.jpg",
        address: "Burger, Sandwich, Fast Food",
        includes: "1 set",
        category: "Breakfast",
        desc:"Idli with Vada is a classic South Indian breakfast combination consisting of steamed rice cakes (idli) served with savory lentil donuts (vada). This traditional dish is often accompanied by coconut chutney and sambar, offering a delightful medley of flavors and textures.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: "2525 + order placed from here recently",
        price: 40,
        rating: "3.8",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 17,
        dish: "Corn Gravy",
        imgdata: "./img/17.jpg",
        address: "Burger, Sandwich, Fast Food",
        includes: "1 bowl (Serves 1)",
        category: "Main Course",
        desc:"Corn Gravy is a flavorful dish made with sweet corn kernels cooked in a rich and creamy gravy. The gravy is typically prepared with onions, tomatoes, ginger-garlic paste, and a blend of spices, creating a delicious and comforting meal.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: "2525 + order placed from here recently",
        price: 120,
        rating: "3.8",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 18,
        dish: "Burger",
        imgdata: "./img/18.jpg",
        address: "Burger, Sandwich, Fast Food",
        includes: "1 glass of juice(200ml)",
        category: "Fast Food/Main Course",
        desc:"A burger is a classic fast-food favorite consisting of a grilled or fried meat patty, typically beef, chicken, or veggie-based, served between two slices of soft bread called buns. It's often layered with cheese, lettuce, tomato, onion, pickles, and condiments like ketchup, mustard, or mayonnaise.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: "2525 + order placed from here recently",
        price: 70,
        rating: "3.8",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
    {
        id: 19,
        dish: "Chicken Leg Piece",
        imgdata: "./img/19.jpg",
        address: "Burger, Sandwich, Fast Food",
        includes: "2 pieces",
        category: "Main Course/Chicken",
        desc:"Chicken Leg Piece refers to the lower portion of a chicken's leg, comprising the drumstick and thigh. It's a flavorful and juicy cut of meat, often grilled, roasted, or fried to perfection, and enjoyed as a standalone dish or as part of a larger meal.",
        delimg: "https://b.zmtcdn.com/data/o2_assets/0b07ef18234c6fdf9365ad1c274ae0631612687510.png?output-format=webp",
        somedata: "2525 + order placed from here recently",
        price: 120,
        rating: "3.8",
        arrimg: "https://b.zmtcdn.com/data/o2_assets/4bf016f32f05d26242cea342f30d47a31595763089.png?output-format=webp",
         qnty:0
    },
];
export default Cardsdata;